pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "fatmaahassana/jenkins-app"
        TAG = "${BUILD_NUMBER}"
        GITOPS_REPO = "https://github.com/FatmaAHassan/gitops-argocd-lab25.git"
    }

    stages {

        stage('Build App') {
            steps {
                echo 'Building application...'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $DOCKER_IMAGE:$TAG ./Jenkins_App"
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh """
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push $DOCKER_IMAGE:$TAG
                    """
                }
            }
        }

        stage('Remove Local Image') {
            steps {
                sh "docker rmi $DOCKER_IMAGE:$TAG || true"
            }
        }

        stage('Update deployment.yaml') {
            steps {
                sh """
                sed -i 's|image:.*|image: $DOCKER_IMAGE:$TAG|' ../gitops-argocd-lab25/deployment.yaml
                """
            }
        }

        stage('Push to GitOps Repo') {
            steps {
                sh """
                cd ../gitops-argocd-lab25
                git config user.email "jenkins@lab.com"
                git config user.name "jenkins"
                git add deployment.yaml
                git commit -m "Update image to $TAG"
                git push origin main
                """
            }
        }
    }
}

