pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "fatmaahassan/jenkins-app"
        TAG = "${BUILD_NUMBER}"
        GITOPS_REPO_URL = "github.com/FatmaAHassan/gitops-argocd-lab25.git"
    }

    stages {
        stage('Build App') {
            steps {
                dir('ArgoCD/Lab25/Jenkins_App') {
                    sh "mvn clean package -DskipTests"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('ArgoCD/Lab25/Jenkins_App') {
                    sh "docker build -t $DOCKER_IMAGE:$TAG ."
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh "echo $PASS | docker login -u $USER --password-stdin"
                    sh "docker push $DOCKER_IMAGE:$TAG"
                }
            }
        }

        stage('Remove Local Image') {
            steps {
                sh "docker rmi $DOCKER_IMAGE:$TAG || true"
            }
        }

        stage('Update & Push to GitOps Repo') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-token', passwordVariable: 'GIT_PASS', usernameVariable: 'GIT_USER')]) {
                    sh """
                    rm -rf gitops-argocd-lab25
                    git clone https://${GIT_USER}:${GIT_PASS}@${GITOPS_REPO_URL}
                    
                    cd gitops-argocd-lab25
                    sed -i 's|image:.*|image: $DOCKER_IMAGE:$TAG|' deployment.yaml
                    
                    git config user.email "jenkins@lab.com"
                    git config user.name "jenkins"
                    git add deployment.yaml
                    git commit -m "Update image to version $TAG"
                    git push origin main
                    """
                }
            }
        }
    }
}
