pipeline {
    agent any

    environment {
        IMAGE_NAME = "fatmaahassan/java_app"
        TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Unit Test') {
            steps {
                dir('Jenkins/Lab22/Lab22-App') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build App') {
            steps {
                dir('Jenkins/Lab22/Lab22-App') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Jenkins/Lab22/Lab22-App') {
                    sh 'docker build -t $IMAGE_NAME:$TAG .'
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $IMAGE_NAME:$TAG
                    '''
                }
            }
        }

        stage('Update deployment.yaml') {
            steps {
                dir('Jenkins/Lab22/Lab22-App') {
                    sh 'sed -i "s|image:.*|image: $IMAGE_NAME:$TAG|" deployment.yaml'
                }
            }
        }
       stage('Deploy to Kubernetes') {
           steps {
               dir('Jenkins/Lab22/Lab22-App') {
                   sh 'kubectl apply -f deployment.yaml'
                 }
            }
        }

    post {
        success {
            echo 'Pipeline Successful 🎉'
        }
        failure {
            echo 'Pipeline Failed ❌'
        }
    }
}

